---
apiVersion: v1
kind: Namespace
metadata:
  name: fly-k8s
  labels:
    name: fly-k8s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: base-map
  namespace: fly-k8s
data:
  fly-name: zhangpanqin
  application.yaml: |
    username: zhangpanqin
    password: 123456
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: fly-k8s
  labels:
    app: busybox
    owner: fly-k8s
spec:
  containers:
    - name: busybox
      image: ghcr.io/zhangpanqin/busybox:0.0.1
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "100Mi"
          cpu: "100m"
      stdin: true
      command: [ "/bin/sh" ]
      env:
        - name: FLY_NAME
          valueFrom:
            configMapKeyRef:
              name: base-map
              key: fly-name
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: base-map
        # An array of keys from the ConfigMap to create as files
        items:
          - key: "game.properties"
            path: "game.properties"
          - key: "application.yaml"
            path: "application.yaml"
