apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: fly-k8s
  labels:
    app: busybox
    owner: fly-k8s
spec:
  containers:
    - name: busybox
      image: ghcr.io/zhangpanqin/busybox:0.0.1
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "100Mi"
          cpu: "100m"
      stdin: true
      command: [ "/bin/sh" ]
